image: docker:latest
services:
  - docker:dind
stages:
  - build
variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/fruetel/machinegenerated.io:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/fruetel/machinegenerated.io:latest

build:
  stage: build
  script:
    - ls -al
    - echo "Running Docker build"
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker run $CONTAINER_TEST_IMAGE ls -al
    - docker push $CONTAINER_TEST_IMAGE
