image: docker:latest
services:
  - docker:dind

before_script:
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose

stages:
  - test
  - publish
variables:
  AWS_ECR_URL: 387451152311.dkr.ecr.eu-west-1.amazonaws.com
  CONTAINER_NAME: ex_retriever

test:
  stage: test
  script:
    - ls -al
    - docker-compose build
    - docker-compose run app test

publish:
  stage: publish
  script:
    - docker build -t ex_retriever .
    - sh ./scripts/login-ecr.sh
    - docker tag ex_retriever:latest $AWS_ECR_URL/$CONTAINER_NAME:latest
    - docker push $AWS_ECR_URL/$CONTAINER_NAME:latest
