image: docker:latest
services:
  - docker:dind

before_script:
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose

stages:
  - build
variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/langbein/ex_retriever:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/langbein/ex_retriever:latest

build:
  stage: build
  script:
    - ls -al
    - echo "Running Docker build"
    - docker build --no-cache -t $CONTAINER_TEST_IMAGE .
    - docker-compose run app test
    - docker push $CONTAINER_TEST_IMAGE
