image: docker:latest
services:
  - docker:dind

before_script:
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

stages:
  - test
  - release
variables:
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/langbein/ex_retriever:latest

test:
  stage: test
  script:
    - ls -al
    - docker-compose build
    - docker-compose run app test

release:
  stage: release
  script:
    - docker build --no-cache -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
