image: docker:latest
services:
  - docker:dind
stages:
  - build
variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/langbein/ex_retriever:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/langbein/ex_retriever:latest

build:
  stage: build
  script:
    - ls -al
    - echo "Running Docker build"
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker-compose run app test
    - docker push $CONTAINER_TEST_IMAGE
