image: docker:latest
services:
  - docker:dind

before_script:
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base

stages:
  - test
  - publish
  - deploy

variables:
  AWS_ECR_URL: 387451152311.dkr.ecr.eu-west-1.amazonaws.com
  AWS_ECR_REGION: eu-west-1
  CONTAINER_NAME: ex_retriever
  CLUSTER_NAME: langbein
  SERVICE_NAME: Crawler

test:
  stage: test
  script:
    - ls -al
    - pip install docker-compose
    - docker-compose build
    - docker-compose run app test

publish:
  stage: publish
  script:
    - docker build -t $CONTAINER_NAME .
    - sh ./scripts/login-ecr.sh
    - docker tag ex_retriever:latest $AWS_ECR_URL/$CONTAINER_NAME:latest
    - docker tag ex_retriever:latest $AWS_ECR_URL/$CONTAINER_NAME:$CI_COMMIT_SHA
    - docker push $AWS_ECR_URL/$CONTAINER_NAME:latest
    - docker push $AWS_ECR_URL/$CONTAINER_NAME:SCI_COMMIT_SHA

deploy:
  stage: deploy
  script:
    - pip install ecs-deploy
    - sh ./scripts/login-ecr.sh
    - ecs deploy ${CLUSTER_NAME} ${SERVICE_NAME} --tag SCI_COMMIT_SHA
